### ISSUE TITLE
Registering an API with a single params break validation

### ISSUE THREAD

**Issue by marcopiraccini** [feugy/mini-service#2]
If we register: 

```
    getXXX: id => getXXX(id).then(res => res.result),
```

...it seems that the id params is not correctly found, so if the API is also valdated with Joi, the API registration fails. 
Workaroud: 

```
```

```
getXXX: (id) => getXXX(id).then(res => res.result),
```

```
```

**Comment by feugy** [comment]
Thank !! Due to the way I try to get parameter names.
I'll fix that as soon as possible

**Comment by feugy** [comment]
[Fixed](https://github.com/feugy/mini-service/commit/26d9e6ae981f39b058f0b4d65fb74eff53faed1d)
